const { createSkillMiddleware } = require('../_shared/middleware')
const apis = require('./apis/index')

const skill = wx.modelContext.createSkill('skills/lease-skill')
skill.use(createSkillMiddleware('lease-skill'))

skill.registerAPI('getActiveLeases', apis.getActiveLeases)
skill.registerAPI('getFinancialReport', apis.getFinancialReport)
skill.registerAPI('getContractOverview', apis.getContractOverview)
skill.registerAPI('getRelativeLeaseExpiry', apis.getRelativeLeaseExpiry)
skill.registerAPI('listGlobalMoveInOutByDateRange', apis.listGlobalMoveInOutByDateRange)
skill.registerAPI('listGlobalMoveInOutForRelativePeriod', apis.listGlobalMoveInOutForRelativePeriod)
skill.registerAPI('getSettlementReport', apis.getSettlementReport)
skill.registerAPI('getLeasePaymentHistory', apis.getLeasePaymentHistory)
skill.registerAPI('getTenantPaymentHistoryByKeyword', apis.getTenantPaymentHistoryByKeyword)
skill.registerAPI('getHousePaymentHistoryByKeyword', apis.getHousePaymentHistoryByKeyword)
skill.registerAPI('getLeaseReport', apis.getLeaseReport)
skill.registerAPI('getArrearsReport', apis.getArrearsReport)
skill.registerAPI('getTenantArrearsByKeyword', apis.getTenantArrearsByKeyword)
skill.registerAPI('getRelativeFutureReceivables', apis.getRelativeFutureReceivables)
skill.registerAPI('getOperatingOverview', apis.getOperatingOverview)
skill.registerAPI('previewCreateLease', apis.previewCreateLease)
skill.registerAPI('confirmCreateLease', apis.confirmCreateLease)
skill.registerAPI('previewPrepayRent', apis.previewPrepayRent)
skill.registerAPI('previewRentCollection', apis.previewRentCollection)
skill.registerAPI('previewRenewLease', apis.previewRenewLease)

console.info('[ai-mode] lease-skill APIs registered')
